### ISSUE TITLE
Any updates for ElasticSearch 1.2.1 and ArangoDB 2.1.2 support?

### ISSUE THREAD

**Issue by texnikru** [triAGENS/elasticsearch-river-arangodb#1]
Any updates for ElasticSearch 1.2.1 and ArangoDB 2.1.2 support?
Thanks!

**Comment by stackmagic** [comment]
@texnikru Hi there.

I've refactored the code a bit and [released something](https://github.com/triAGENS/elasticsearch-river-arangodb/releases/tag/v0.3.0) that should work with ArangoDB up to 2.2.

I'm working on support for ArangoDB 2.2 and higher now.

**Comment by fceller** [comment]
Cool, thank you very much

**Comment by texnikru** [comment]
Sounds good. Thank you!
